#!/bin/bash

set -euo pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

payload="$(cat <&0)"

load_pubkey "$payload"
configure_https_tunnel "$payload"
configure_git_ssl_verification "$payload"
configure_credentials "$payload"

uri=$(jq -r '.source.uri // ""' <<< "$payload")
include_git_heads=$(jq -r '.source.include_git_heads // ""' <<< "$payload")
branch_regex=$(jq -r '.source.branch_regex // ""' <<< "$payload")
prev_branches=$(jq -r '.version.branches // ""' <<< "$payload")
git_config_payload=$(jq -r '.source.git_config // []' <<< "$payload")

configure_git_global "$payload"

python3 $(dirname $0)/run-check.py "$payload" >&3
